language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - 1.x
  - stable
  - master

install:
  - go get github.com/llgcode/draw2d/draw2dimg
  - go get github.com/drix00/goElectron


before_install:
  - cp .netrc ~
  - chmod 600 .netrc